New plugin API

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -3,6 +3,7 @@
 set -euo pipefail
 shopt -s inherit_errexit 2>/dev/null || true
 
+[[ -z ${ASDF_DOWNLOAD_PATH+x} ]] && echo "ASDF_DOWNLOAD_PATH is required" && exit 1
 [[ -z ${ASDF_INSTALL_TYPE+x} ]] && echo "ASDF_INSTALL_TYPE is required" && exit 1
 [[ -z ${ASDF_INSTALL_VERSION+x} ]] && echo "ASDF_INSTALL_VERSION is required" && exit 1
 [[ -z ${ASDF_INSTALL_PATH+x} ]] && echo "ASDF_INSTALL_PATH is required" && exit 1
@@ -19,18 +20,8 @@ function gh_curl() {
 
 function install() {
 	# set -x
-	local install_type=$1
-	[[ ${install_type} != "version" ]] && echo "install type, ${install_type}, is not supported" && exit 1
 
-	local prefix="v"
-	local version=$2
-	local install_path=$3
-
-	local tmp_download_dir
-
-	tmp_download_dir=$(mktemp -d -t asdf.XXXXXXXX)
-
-	local bin_install_path="${install_path}/bin"
+	./download
 
 	local platform
 	platform=$(echo "${ASDF_PLATFORM:-$(uname -s)}" | tr 'A-Z' 'a-z')
@@ -44,35 +35,18 @@ function install() {
 
 	local download_url
 
-	local repo="fwdcloudsec/granted"
-	local download_filename="granted_${version}_${platform}_${arch}.tar.gz"
+	local download_filename="granted_${ASDF_INSTALL_VERSION}_${platform}_${arch}.tar.gz"
 
-	if [[ -n ${GITHUB_TOKEN-} ]] || [[ -n ${GITHUB_API_TOKEN-} ]]; then
-		local asset_url
-		asset_url="https://api.github.com/repos/${repo}/releases/tags/${prefix}${version}"
-		download_url=$(gh_curl -H "Accept: application/vnd.github.v3.raw" "${asset_url}" | jq -r ".assets | map(select(.name == \"${download_filename}\"))[0].url")
-		if [[ ${download_url} == null ]]; then
-			echo "Asset ${download_filename} not found in a release ${prefix}${version}."
-			exit 1
-		fi
-	else
-		download_url="https://github.com/${repo}/releases/download/${prefix}${version}/${download_filename}"
-	fi
-
-	echo "Downloading ${download_filename} from release ${prefix}${version} from ${download_url}"
-
-	mkdir -p "${tmp_download_dir}"
-
-	pushd "${tmp_download_dir}" >/dev/null
+	pushd "${ASDF_DOWNLOAD_PATH:=}" >/dev/null
 
 	gh_curl -H "Accept: application/octet-stream" -o "${download_filename}" "${download_url}"
 
-	mkdir -p "${bin_install_path}"
+	mkdir -p "${ASDF_INSTALL_PATH}"
 
-	tar -zxf "${download_filename}" -C "${bin_install_path}"
+	tar -zxf "${download_filename}" -C "${ASDF_INSTALL_PATH}"
 
-	if ! [[ -f ${bin_install_path}/assumego ]]; then
-		ln -s granted "${bin_install_path}/assumego"
+	if ! [[ -f ${ASDF_INSTALL_PATH}/assumego ]]; then
+		ln -s granted "${ASDF_INSTALL_PATH}/assumego"
 	fi
 
 	echo "Granted is installed. Please add following line to your ~/.bashrc, ~/.bash_profile, ~/.profile, ~/.zshenv or ~/.config/fish/config.fish:"
@@ -83,4 +57,4 @@ function install() {
 	popd >/dev/null
 }
 
-install "${ASDF_INSTALL_TYPE}" "${ASDF_INSTALL_VERSION}" "${ASDF_INSTALL_PATH}"
+install
